- name: Installing nginx
  hosts: web
  become: yes
  tasks:
    - name: insall ngnix
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enable: yes


