- name: play_level_variables
  hosts: local
  connection: local
  vars:
    course: "Devops"
    duration: "6"
    trainer: "shiva"

  tasks: 
    - name: Print variables
      ansible.builtin.debug:
      msg: "course is {{course}}, duration is {{duration}}, trainer is {{trainer}}"

