- name: Variables_types
  hosts: local
  connection: local
  vars:
    program: "Devsecops"
    duration: 140
    IS_LIVE: true
    Details: #map 
      Months: 4
      trainer: "siva"
    Topics: #list
    - Linux
    - Shell
    - Ansible
  tasks:
    - name: Print variables
      ansible.builtin.debug:
        msg: |
          Program : {{ program }}
          Duration: {{ duration }}
          Details:  {{ Details }}
          Topics:   {{ Topics }}
      when: IS_LIVE 

- name: check numer less or more
  hosts: local
  connection: local
  vars:
    Number1: 40
  vars_prompt:
    - name: Number2
      prompt: please enter Number
      private: false
  tasks:
    - name: Number1 is less than Number2
      ansible.builtin.debug:
        msg: "{{ Number1 }} is LESS than {{ Number2 }}"
      when: Number1 < (Number2 | int)

    - name: Number1 is greater than or equal to Number2
      ansible.builtin.debug:
        msg: "{{ Number1 }} is GREATER than or EQUAL to {{ Number2 }}"
      when: Number1 >= (Number2 | int)     
    