- name: gathering facts
  hosts: local
  connection: local
  tasks:
    - name: Print facts
      ansible.builtin.debug:
        #msg: "{{ ansible_facts }}"

    - name: check red hat or not
      ansible.builtin.debug:
        msg: "yes Red hat"
      when: ansible_facts.os_family == "RedHat"     