- name: shell
  hosts: local
  become: yes
  connection: local
  tasks:
    - name: command 
      ansible.builtin.shell: ls -lsi etc/
      register: users_output

    - name: Print
      ansible.builtin.debug:
        msg: "{{ users_output }}"
